let
    Source = Csv.Document(File.Contents("C:\Users\rafae\OneDrive\Documents\web_scrapping\data\players.csv"),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"player_id", type text}, {"name", type text}, {"position", type text}, {"height_cm", Int64.Type}, {"weight_kg", Int64.Type}, {"age", Int64.Type}, {"nationality", type text}, {"since_year", type text}, {"caps", type text}, {"matches", type text}, {"tries", type text}, {"points", type text}, {"url", type text}}),
    #"Valeur remplacée" = Table.ReplaceValue(#"Type modifié",".0","",Replacer.ReplaceText,{"points"}),
    #"Valeur remplacée1" = Table.ReplaceValue(#"Valeur remplacée",".0","",Replacer.ReplaceText,{"tries"}),
    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1",".0","",Replacer.ReplaceText,{"matches"}),
    #"Valeur remplacée3" = Table.ReplaceValue(#"Valeur remplacée2",".0","",Replacer.ReplaceText,{"caps"}),
    #"Valeur remplacée4" = Table.ReplaceValue(#"Valeur remplacée3",".0","",Replacer.ReplaceText,{"since_year"}),
    #"Type modifié1" = Table.TransformColumnTypes(#"Valeur remplacée4",{{"since_year", Int64.Type}, {"caps", Int64.Type}, {"matches", Int64.Type}, {"tries", Int64.Type}, {"points", Int64.Type}}),
    #"Valeur remplacée5" = Table.ReplaceValue(#"Type modifié1","Rohan JANSE VAN RENSBURG","Rohan JANSEVANRENSBURG",Replacer.ReplaceText,{"name"}),
    #"Valeur remplacée6" = Table.ReplaceValue(#"Valeur remplacée5","Jean-Luc DU PREEZ","Jean-Luc DUPREEZ",Replacer.ReplaceText,{"name"}),
    #"Fractionner la colonne par délimiteur" = Table.SplitColumn(#"Valeur remplacée6", "name", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"name.1", "name.2"}),
    #"Type modifié2" = Table.TransformColumnTypes(#"Fractionner la colonne par délimiteur",{{"name.1", type text}, {"name.2", type text}}),
    #"Valeur remplacée7" = Table.ReplaceValue(#"Type modifié2","JANSEVANRENSBURG","JANSE VAN RENSBURG",Replacer.ReplaceText,{"name.2"}),
    #"Valeur remplacée8" = Table.ReplaceValue(#"Valeur remplacée7","DUPREEZ","DU PREEZ",Replacer.ReplaceText,{"name.2"}),
    #"Colonnes renommées" = Table.RenameColumns(#"Valeur remplacée8",{{"name.1", "prenom"}, {"name.2", "nom"}}),
    #"Valeur remplacée9" = Table.ReplaceValue(#"Colonnes renommées","SOUTH AFRICA","Afrique du Sud",Replacer.ReplaceText,{"nationality"}),
    #"Valeur remplacée10" = Table.ReplaceValue(#"Valeur remplacée9","FRA","France",Replacer.ReplaceText,{"nationality"}),
    #"Valeur remplacée11" = Table.ReplaceValue(#"Valeur remplacée10","ITA","Italie",Replacer.ReplaceText,{"nationality"}),
    #"Valeur remplacée12" = Table.ReplaceValue(#"Valeur remplacée11","Nouvelle-Zélande","NZ",Replacer.ReplaceText,{"nationality"}),
    #"Colonnes renommées1" = Table.RenameColumns(#"Valeur remplacée12",{{"nationality", "nationalité"}}),
    #"Valeur remplacée13" = Table.ReplaceValue(#"Colonnes renommées1","-","/",Replacer.ReplaceText,{"nationalité"}),
    #"Fractionner la colonne par délimiteur1" = Table.SplitColumn(#"Valeur remplacée13", "nationalité", Splitter.SplitTextByDelimiter("/", QuoteStyle.Csv), {"nationalité.1", "nationalité.2"}),
    #"Type modifié3" = Table.TransformColumnTypes(#"Fractionner la colonne par délimiteur1",{{"nationalité.1", type text}, {"nationalité.2", type text}}),
    #"Valeur remplacée14" = Table.ReplaceValue(#"Type modifié3","FranceNCE","France",Replacer.ReplaceText,{"nationalité.1"}),
    #"Valeur remplacée15" = Table.ReplaceValue(#"Valeur remplacée14","NZ","Nouvelle-Zélande",Replacer.ReplaceText,{"nationalité.1"}),
    #"Valeur remplacée16" = Table.ReplaceValue(#"Valeur remplacée15","NZ","Nouvelle-Zélande",Replacer.ReplaceText,{"nationalité.2"}),
    #"Valeur remplacée17" = Table.ReplaceValue(#"Valeur remplacée16","3 ème","3ème",Replacer.ReplaceText,{"position"}),
    #"Valeur remplacée18" = Table.ReplaceValue(#"Valeur remplacée17","2 ème","2ème",Replacer.ReplaceText,{"position"}),
    #"Colonnes renommées2" = Table.RenameColumns(#"Valeur remplacée18",{{"url", "url_page"}}),
    #"Requêtes fusionnées" = Table.NestedJoin(#"Colonnes renommées2", {"player_id"}, PlayersPhotos, {"player_id"}, "PlayersPhotos", JoinKind.LeftOuter),
    #"PlayersPhotos développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "PlayersPhotos", {"image_url"}, {"image_url"}),
    #"Valeur remplacée19" = Table.ReplaceValue(#"PlayersPhotos développé",null,"https://www.ubbrugby.com/application/uploads/idev_team/thumbs/thumb_player_detail_896x728_inset_up_palu_-_recadre.png",Replacer.ReplaceValue,{"image_url"}),
    #"Colonnes renommées3" = Table.RenameColumns(#"Valeur remplacée19",{{"image_url", "photos_url"}}),
    #"Valeur remplacée20" = Table.ReplaceValue(#"Colonnes renommées3","France ","France",Replacer.ReplaceText,{"nationalité.1"}),
    #"Valeur remplacée21" = Table.ReplaceValue(#"Valeur remplacée20","Nouvelle-Zélande ","Nouvelle-Zélande",Replacer.ReplaceText,{"nationalité.1"}),
    #"Valeur remplacée22" = Table.ReplaceValue(#"Valeur remplacée21","Écosse","Ecosse",Replacer.ReplaceText,{"nationalité.1"}),
    #"Requêtes fusionnées1" = Table.NestedJoin(#"Valeur remplacée22", {"nationalité.1"}, nationality_images, {"country"}, "nationality_images", JoinKind.LeftOuter),
    #"nationality_images développé" = Table.ExpandTableColumn(#"Requêtes fusionnées1", "nationality_images", {"raw_url"}, {"nationality_images.raw_url"}),
    #"Valeur remplacée23" = Table.ReplaceValue(#"nationality_images développé","Australie","Australie",Replacer.ReplaceText,{"nationalité.1"}),
    #"Requêtes fusionnées2" = Table.NestedJoin(#"Valeur remplacée23", {"nationalité.1"}, nationality_images, {"raw_url"}, "nationality_images", JoinKind.LeftOuter),
    #"Colonnes renommées4" = Table.RenameColumns(#"Requêtes fusionnées2",{{"nationality_images.raw_url", "FlagNationality"}})
in
    #"Colonnes renommées4"